# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PanelKGroupTransfer_v28.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.setObjectName("Dialog")
        self.resize(372, 189)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(0, 0, 371, 189))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.de_TransferDate = QtWidgets.QDateEdit(self.frame)
        self.de_TransferDate.setGeometry(QtCore.QRect(150, 110, 201, 22))
        self.de_TransferDate.setObjectName("de_TransferDate")
        self.cb_ParenKbjName = QtWidgets.QComboBox(self.frame)
        self.cb_ParenKbjName.setGeometry(QtCore.QRect(150, 50, 201, 22))
        self.cb_ParenKbjName.setObjectName("cb_ParenKbjName")
        self.cb_ChildKbjName = QtWidgets.QComboBox(self.frame)
        self.cb_ChildKbjName.setGeometry(QtCore.QRect(150, 80, 201, 22))
        self.cb_ChildKbjName.setObjectName("cb_ChildKbjName")
        self.btn_Transfer = QtWidgets.QPushButton(self.frame)
        self.btn_Transfer.setGeometry(QtCore.QRect(264, 150, 91, 23))
        self.btn_Transfer.setObjectName("btn_Transfer")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 83, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 106, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 53, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Transfer.setText(_translate("Dialog", "Переместить"))
        self.label_3.setText(_translate("Dialog", "Имя подобъекта:"))
        self.label_4.setText(_translate("Dialog", "Дата перемещения:"))
        self.label_2.setText(_translate("Dialog", "Куда переместить:"))
        self.label.setText(_translate("Dialog", "Перемещение комплектующих"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
