# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PanelGlobStatEdit_v25.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.setObjectName("Dialog")
        self.resize(372, 214)
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(0, 0, 371, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cb_TypeStuff = QtWidgets.QComboBox(self.frame)
        self.cb_TypeStuff.setGeometry(QtCore.QRect(150, 60, 201, 22))
        self.cb_TypeStuff.setObjectName("cb_TypeStuff")
        self.cb_ModelStuff = QtWidgets.QComboBox(self.frame)
        self.cb_ModelStuff.setGeometry(QtCore.QRect(150, 90, 201, 22))
        self.cb_ModelStuff.setObjectName("cb_ModelStuff")
        self.btn_AddStuff = QtWidgets.QPushButton(self.frame)
        self.btn_AddStuff.setGeometry(QtCore.QRect(280, 180, 75, 23))
        self.btn_AddStuff.setObjectName("btn_AddStuff")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 71, 16))
        self.label_4.setObjectName("label_4")
        self.cb_Num = QtWidgets.QComboBox(self.frame)
        self.cb_Num.setGeometry(QtCore.QRect(150, 120, 61, 22))
        self.cb_Num.setObjectName("cb_Num")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_AddStuff.setText(_translate("Dialog", "Добавить"))
        self.label_3.setText(_translate("Dialog", "Модель"))
        self.label_2.setText(_translate("Dialog", "Тип"))
        self.label.setText(_translate("Dialog", "Оборудование | Редактирование"))
        self.label_4.setText(_translate("Dialog", "Количество"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
